In [65]:
import pandas as pd
import numpy as np
#from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score

In [66]:
strain=pd.read_csv("/Users/pratikgade123/Desktop/Pandas/SalaryData_Test.csv")
stest=pd.read_csv("/Users/pratikgade123/Desktop/Pandas/SalaryData_Train.csv")

In [67]:
strain

age      workclass      education  educationno        maritalstatus  \
0       25        Private           11th            7        Never-married   
1       38        Private        HS-grad            9   Married-civ-spouse   
2       28      Local-gov     Assoc-acdm           12   Married-civ-spouse   
3       44        Private   Some-college           10   Married-civ-spouse   
4       34        Private           10th            6        Never-married   
...    ...            ...            ...          ...                  ...   
15055   33        Private      Bachelors           13        Never-married   
15056   39        Private      Bachelors           13             Divorced   
15057   38        Private      Bachelors           13   Married-civ-spouse   
15058   44        Private      Bachelors           13             Divorced   
15059   35   Self-emp-inc      Bachelors           13   Married-civ-spouse   

               occupation    relationship                 race      sex  \
0       Machine-op-inspct       Own-child                Black     Male   
1         Farming-fishing         Husband                White     Male   
2         Protective-serv         Husband                White     Male   
3       Machine-op-inspct         Husband                Black     Male   
4           Other-service   Not-in-family                White     Male   
...                   ...             ...                  ...      ...   
15055      Prof-specialty       Own-child                White     Male   
15056      Prof-specialty   Not-in-family                White   Female   
15057      Prof-specialty         Husband                White     Male   
15058        Adm-clerical       Own-child   Asian-Pac-Islander     Male   
15059     Exec-managerial         Husband                White     Male   

       capitalgain  capitalloss  hoursperweek          native  Salary  
0                0            0            40   United-States   <=50K  
1                0            0            50   United-States   <=50K  
2                0            0            40   United-States    >50K  
3             7688            0            40   United-States    >50K  
4                0            0            30   United-States   <=50K  
...            ...          ...           ...             ...     ...  
15055            0            0            40   United-States   <=50K  
15056            0            0            36   United-States   <=50K  
15057            0            0            50   United-States   <=50K  
15058         5455            0            40   United-States   <=50K  
15059            0            0            60   United-States    >50K  

[15060 rows x 14 columns]

In [68]:
stest

age          workclass    education  educationno        maritalstatus  \
0       39          State-gov    Bachelors           13        Never-married   
1       50   Self-emp-not-inc    Bachelors           13   Married-civ-spouse   
2       38            Private      HS-grad            9             Divorced   
3       53            Private         11th            7   Married-civ-spouse   
4       28            Private    Bachelors           13   Married-civ-spouse   
...    ...                ...          ...          ...                  ...   
30156   27            Private   Assoc-acdm           12   Married-civ-spouse   
30157   40            Private      HS-grad            9   Married-civ-spouse   
30158   58            Private      HS-grad            9              Widowed   
30159   22            Private      HS-grad            9        Never-married   
30160   52       Self-emp-inc      HS-grad            9   Married-civ-spouse   

               occupation    relationship    race      sex  capitalgain  \
0            Adm-clerical   Not-in-family   White     Male         2174   
1         Exec-managerial         Husband   White     Male            0   
2       Handlers-cleaners   Not-in-family   White     Male            0   
3       Handlers-cleaners         Husband   Black     Male            0   
4          Prof-specialty            Wife   Black   Female            0   
...                   ...             ...     ...      ...          ...   
30156        Tech-support            Wife   White   Female            0   
30157   Machine-op-inspct         Husband   White     Male            0   
30158        Adm-clerical       Unmarried   White   Female            0   
30159        Adm-clerical       Own-child   White     Male            0   
30160     Exec-managerial            Wife   White   Female        15024   

       capitalloss  hoursperweek          native  Salary  
0                0            40   United-States   <=50K  
1                0            13   United-States   <=50K  
2                0            40   United-States   <=50K  
3                0            40   United-States   <=50K  
4                0            40            Cuba   <=50K  
...            ...           ...             ...     ...  
30156            0            38   United-States   <=50K  
30157            0            40   United-States    >50K  
30158            0            40   United-States   <=50K  
30159            0            20   United-States   <=50K  
30160            0            40   United-States    >50K  

[30161 rows x 14 columns]

In [69]:
stest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            30161 non-null  int64 
 1   workclass      30161 non-null  object
 2   education      30161 non-null  object
 3   educationno    30161 non-null  int64 
 4   maritalstatus  30161 non-null  object
 5   occupation     30161 non-null  object
 6   relationship   30161 non-null  object
 7   race           30161 non-null  object
 8   sex            30161 non-null  object
 9   capitalgain    30161 non-null  int64 
 10  capitalloss    30161 non-null  int64 
 11  hoursperweek   30161 non-null  int64 
 12  native         30161 non-null  object
 13  Salary         30161 non-null  object
dtypes: int64(5), object(9)
memory usage: 3.2+ MB


In [70]:
stest.shape

(30161, 14)

In [71]:
strain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15060 entries, 0 to 15059
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            15060 non-null  int64 
 1   workclass      15060 non-null  object
 2   education      15060 non-null  object
 3   educationno    15060 non-null  int64 
 4   maritalstatus  15060 non-null  object
 5   occupation     15060 non-null  object
 6   relationship   15060 non-null  object
 7   race           15060 non-null  object
 8   sex            15060 non-null  object
 9   capitalgain    15060 non-null  int64 
 10  capitalloss    15060 non-null  int64 
 11  hoursperweek   15060 non-null  int64 
 12  native         15060 non-null  object
 13  Salary         15060 non-null  object
dtypes: int64(5), object(9)
memory usage: 1.6+ MB


In [72]:
strain.shape

(15060, 14)

In [73]:
strain.workclass.unique()

array([' Private', ' Local-gov', ' Self-emp-not-inc', ' Federal-gov',
       ' State-gov', ' Self-emp-inc', ' Without-pay'], dtype=object)

In [74]:
stest.workclass.unique()

array([' State-gov', ' Self-emp-not-inc', ' Private', ' Federal-gov',
       ' Local-gov', ' Self-emp-inc', ' Without-pay'], dtype=object)

In [75]:
strain.columns
stest.columns
stringcol=['workclass','education','maritalstatus','occupation','relationship','race','sex','native']

In [76]:
from sklearn import preprocessing

In [77]:
label_encoder=preprocessing.LabelEncoder()
for i in stringcol:
    strain[i]=label_encoder.fit_transform(strain[i])
    stest[i]=label_encoder.fit_transform(stest[i])

In [78]:
strain.head()

age  workclass  education  educationno  maritalstatus  occupation  \
0   25          2          1            7              4           6   
1   38          2         11            9              2           4   
2   28          1          7           12              2          10   
3   44          2         15           10              2           6   
4   34          2          0            6              4           7   

   relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  \
0             3     2    1            0            0            40      37   
1             0     4    1            0            0            50      37   
2             0     4    1            0            0            40      37   
3             0     2    1         7688            0            40      37   
4             1     4    1            0            0            30      37   

   Salary  
0   <=50K  
1   <=50K  
2    >50K  
3    >50K  
4   <=50K

In [79]:
#coverting Y column in train test both 
strain['Salary'] = label_encoder.fit_transform(strain['Salary'])

In [80]:
stest['Salary'] = label_encoder.fit_transform(stest['Salary'])

In [81]:
strain

age  workclass  education  educationno  maritalstatus  occupation  \
0       25          2          1            7              4           6   
1       38          2         11            9              2           4   
2       28          1          7           12              2          10   
3       44          2         15           10              2           6   
4       34          2          0            6              4           7   
...    ...        ...        ...          ...            ...         ...   
15055   33          2          9           13              4           9   
15056   39          2          9           13              0           9   
15057   38          2          9           13              2           9   
15058   44          2          9           13              0           0   
15059   35          3          9           13              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
0                 3     2    1            0            0            40   
1                 0     4    1            0            0            50   
2                 0     4    1            0            0            40   
3                 0     2    1         7688            0            40   
4                 1     4    1            0            0            30   
...             ...   ...  ...          ...          ...           ...   
15055             3     4    1            0            0            40   
15056             1     4    0            0            0            36   
15057             0     4    1            0            0            50   
15058             3     1    1         5455            0            40   
15059             0     4    1            0            0            60   

       native  Salary  
0          37       0  
1          37       0  
2          37       1  
3          37       1  
4          37       0  
...       ...     ...  
15055      37       0  
15056      37       0  
15057      37       0  
15058      37       0  
15059      37       1  

[15060 rows x 14 columns]

In [82]:
stest

age  workclass  education  educationno  maritalstatus  occupation  \
0       39          5          9           13              4           0   
1       50          4          9           13              2           3   
2       38          2         11            9              0           5   
3       53          2          1            7              2           5   
4       28          2          9           13              2           9   
...    ...        ...        ...          ...            ...         ...   
30156   27          2          7           12              2          12   
30157   40          2         11            9              2           6   
30158   58          2         11            9              6           0   
30159   22          2         11            9              4           0   
30160   52          3         11            9              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
0                 1     4    1         2174            0            40   
1                 0     4    1            0            0            13   
2                 1     4    1            0            0            40   
3                 0     2    1            0            0            40   
4                 5     2    0            0            0            40   
...             ...   ...  ...          ...          ...           ...   
30156             5     4    0            0            0            38   
30157             0     4    1            0            0            40   
30158             4     4    0            0            0            40   
30159             3     4    1            0            0            20   
30160             5     4    0        15024            0            40   

       native  Salary  
0          37       0  
1          37       0  
2          37       0  
3          37       0  
4           4       0  
...       ...     ...  
30156      37       0  
30157      37       1  
30158      37       0  
30159      37       0  
30160      37       1  

[30161 rows x 14 columns]

In [83]:
strainx=strain.iloc[:,:1]
strainy=strain.iloc[:,1]
stestx=stest.iloc[:,:1]
stesty=stest.iloc[:,1]

In [84]:
strainx.shape ,strainy.shape, stestx.shape, stesty.shape,

((15060, 1), (15060,), (30161, 1), (30161,))

In [85]:
model= SVC()

model.fit(strainx,strainy)

SVC()

In [86]:
Y_pred = model.predict(strainx)
Y_pred

array([2, 2, 2, ..., 2, 2, 2])

In [87]:
print(confusion_matrix(strainy, Y_pred))

[[    0     0   463     0     0     0     0]
 [    0     0  1033     0     0     0     0]
 [    0     0 11021     0     0     0     0]
 [    0     0   572     0     0     0     0]
 [    0     0  1297     0     0     0     0]
 [    0     0   667     0     0     0     0]
 [    0     0     7     0     0     0     0]]


In [88]:
print(classification_report(strainy, Y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       463
           1       0.00      0.00      0.00      1033
           2       0.73      1.00      0.85     11021
           3       0.00      0.00      0.00       572
           4       0.00      0.00      0.00      1297
           5       0.00      0.00      0.00       667
           6       0.00      0.00      0.00         7

    accuracy                           0.73     15060
   macro avg       0.10      0.14      0.12     15060
weighted avg       0.54      0.73      0.62     15060



/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [89]:
param_grid = {'C' : [1, 5, 10, 15], 'gamma' : [1, 0.1, 0.01, 0.001], 'kernel' : ['rbf']}

In [90]:
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3,  cv = 4)

In [91]:
grid.fit(strainx,strainy)

Fitting 4 folds for each of 16 candidates, totalling 64 fits
[CV 1/4] END ..........C=1, gamma=1, kernel=rbf;, score=0.732 total time=   4.7s
[CV 2/4] END ..........C=1, gamma=1, kernel=rbf;, score=0.732 total time=   4.7s
[CV 3/4] END ..........C=1, gamma=1, kernel=rbf;, score=0.732 total time=   4.7s
[CV 4/4] END ..........C=1, gamma=1, kernel=rbf;, score=0.732 total time=   4.7s
[CV 1/4] END ........C=1, gamma=0.1, kernel=rbf;, score=0.732 total time=   4.7s
[CV 2/4] END ........C=1, gamma=0.1, kernel=rbf;, score=0.732 total time=   4.8s
[CV 3/4] END ........C=1, gamma=0.1, kernel=rbf;, score=0.732 total time=   4.8s
[CV 4/4] END ........C=1, gamma=0.1, kernel=rbf;, score=0.732 total time=   4.8s
[CV 1/4] END .......C=1, gamma=0.01, kernel=rbf;, score=0.732 total time=   4.8s
[CV 2/4] END .......C=1, gamma=0.01, kernel=rbf;, score=0.732 total time=   4.8s
[CV 3/4] END .......C=1, gamma=0.01, kernel=rbf;, score=0.732 total time=   4.8s
[CV 4/4] END .......C=1, gamma=0.01, kernel=rbf;

GridSearchCV(cv=4, estimator=SVC(),
             param_grid={'C': [1, 5, 10, 15], 'gamma': [1, 0.1, 0.01, 0.001],
                         'kernel': ['rbf']},
             verbose=3)

In [92]:
grid.best_params_ , grid.best_score_ 

({'C': 1, 'gamma': 1, 'kernel': 'rbf'}, 0.7318061088977423)

In [93]:
grid_pred = grid.predict(stestx)

In [94]:
acc = accuracy_score(stesty, grid_pred) * 100

In [95]:
acc

73.88680746659594

In [96]:
print(confusion_matrix(stesty, grid_pred))

[[    0     0   943     0     0     0     0]
 [    0     0  2067     0     0     0     0]
 [    0     0 22281     0     4     0     0]
 [    0     0  1072     0     2     0     0]
 [    0     0  2495     0     4     0     0]
 [    0     0  1279     0     0     0     0]
 [    0     0    14     0     0     0     0]]


In [97]:
print(classification_report(stesty, grid_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       943
           1       0.00      0.00      0.00      2067
           2       0.74      1.00      0.85     22285
           3       0.00      0.00      0.00      1074
           4       0.40      0.00      0.00      2499
           5       0.00      0.00      0.00      1279
           6       0.00      0.00      0.00        14

    accuracy                           0.74     30161
   macro avg       0.16      0.14      0.12     30161
weighted avg       0.58      0.74      0.63     30161



/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# forest fire

In [98]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [99]:
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

In [100]:
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score

In [101]:
ffs=pd.read_csv("/Users/pratikgade123/Desktop/Pandas/forestfires.csv")
ffs

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  monthfeb  \
0     mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...         0   
1     oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...         0   
2     oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...         0   
3     mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...         0   
4     mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...         0   
..    ...  ...   ...    ...    ...   ...   ...  ..   ...   ...  ...       ...   
512   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  ...         0   
513   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  ...         0   
514   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  ...         0   
515   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  ...         0   
516   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0  ...         0   

     monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0           0         0         0         1         0         0         0   
1           0         0         0         0         0         0         1   
2           0         0         0         0         0         0         1   
3           0         0         0         1         0         0         0   
4           0         0         0         1         0         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         1         0   

     monthsep  size_category  
0           0          small  
1           0          small  
2           0          small  
3           0          small  
4           0          small  
..        ...            ...  
512         0          large  
513         0          large  
514         0          large  
515         0          small  
516         0          small  

[517 rows x 31 columns]

In [102]:
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()
ffs['month'] = label_encoder.fit_transform(ffs['month'])
ffs['day'] = label_encoder.fit_transform(ffs['day'])
ffs['size_category'] = label_encoder.fit_transform(ffs['size_category'])

In [103]:
ffs

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  \
0        7    0  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...   
1       10    5  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...   
2       10    2  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...   
3        7    0  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...   
4        7    3  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...   
..     ...  ...   ...    ...    ...   ...   ...  ..   ...   ...  ...   
512      1    3  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  ...   
513      1    3  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  ...   
514      1    3  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  ...   
515      1    2  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  ...   
516      9    5  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0  ...   

     monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  \
0           0         0         0         0         1         0         0   
1           0         0         0         0         0         0         0   
2           0         0         0         0         0         0         0   
3           0         0         0         0         1         0         0   
4           0         0         0         0         1         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         0         1   

     monthoct  monthsep  size_category  
0           0         0              1  
1           1         0              1  
2           1         0              1  
3           0         0              1  
4           0         0              1  
..        ...       ...            ...  
512         0         0              0  
513         0         0              0  
514         0         0              0  
515         0         0              1  
516         0         0              1  

[517 rows x 31 columns]

In [104]:
ffs=ffs.drop(ffs.columns[0:2],axis=1)
ffs.head()

FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  dayfri  ...  monthfeb  \
0  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0       1  ...         0   
1  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0       0  ...         0   
2  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0       0  ...         0   
3  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0       1  ...         0   
4  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0       0  ...         0   

   monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0         0         0         0         1         0         0         0   
1         0         0         0         0         0         0         1   
2         0         0         0         0         0         0         1   
3         0         0         0         1         0         0         0   
4         0         0         0         1         0         0         0   

   monthsep  size_category  
0         0              1  
1         0              1  
2         0              1  
3         0              1  
4         0              1  

[5 rows x 29 columns]

In [105]:
ffs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 29 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   FFMC           517 non-null    float64
 1   DMC            517 non-null    float64
 2   DC             517 non-null    float64
 3   ISI            517 non-null    float64
 4   temp           517 non-null    float64
 5   RH             517 non-null    int64  
 6   wind           517 non-null    float64
 7   rain           517 non-null    float64
 8   area           517 non-null    float64
 9   dayfri         517 non-null    int64  
 10  daymon         517 non-null    int64  
 11  daysat         517 non-null    int64  
 12  daysun         517 non-null    int64  
 13  daythu         517 non-null    int64  
 14  daytue         517 non-null    int64  
 15  daywed         517 non-null    int64  
 16  monthapr       517 non-null    int64  
 17  monthaug       517 non-null    int64  
 18  monthdec  

Splitting the data into x and y as input and output# Splitting the data into x and y as input and output

In [106]:
x= ffs.iloc[:,0:28]
y = ffs.iloc[:,28]

In [107]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
array_x=scaler.fit_transform(x)

In [108]:
array_x

array([[-8.05959472e-01, -1.32332557e+00, -1.83047676e+00, ...,
        -4.40225453e-02, -1.72859706e-01, -7.06081245e-01],
       [-8.10203395e-03, -1.17954077e+00,  4.88890915e-01, ...,
        -4.40225453e-02,  5.78503817e+00, -7.06081245e-01],
       [-8.10203395e-03, -1.04982188e+00,  5.60715454e-01, ...,
        -4.40225453e-02,  5.78503817e+00, -7.06081245e-01],
       ...,
       [-1.64008316e+00, -8.46647711e-01,  4.74768113e-01, ...,
        -4.40225453e-02, -1.72859706e-01, -7.06081245e-01],
       [ 6.80956663e-01,  5.49002541e-01,  2.69382214e-01, ...,
        -4.40225453e-02, -1.72859706e-01, -7.06081245e-01],
       [-2.02087875e+00, -1.68591332e+00, -1.78044169e+00, ...,
         2.27156334e+01, -1.72859706e-01, -7.06081245e-01]])

In [109]:
x=pd.DataFrame(array_x)
x

0         1         2         3         4         5         6   \
0   -0.805959 -1.323326 -1.830477 -0.860946 -1.842640  0.411724  1.498614   
1   -0.008102 -1.179541  0.488891 -0.509688 -0.153278 -0.692456 -1.741756   
2   -0.008102 -1.049822  0.560715 -0.509688 -0.739383 -0.692456 -1.518282   
3    0.191362 -1.212361 -1.898266 -0.004756 -1.825402  3.233519 -0.009834   
4   -0.243833 -0.931043 -1.798600  0.126966 -1.291012  3.356206 -1.238940   
..        ...       ...       ...       ...       ...       ...       ...   
512 -1.640083 -0.846648  0.474768 -1.563460  1.536084 -0.753800 -0.736124   
513 -1.640083 -0.846648  0.474768 -1.563460  0.519019  1.638592  0.995798   
514 -1.640083 -0.846648  0.474768 -1.563460  0.398350  1.577248  1.498614   
515  0.680957  0.549003  0.269382  0.500176  1.156839 -0.140366 -0.009834   
516 -2.020879 -1.685913 -1.780442 -1.739089 -1.222058 -0.815143  0.269509   

           7         8         9   ...        18        19        20  \
0   -0.073268 -0.202020  2.254407  ... -0.133103 -0.200603 -0.062318   
1   -0.073268 -0.202020 -0.443576  ... -0.133103 -0.200603 -0.062318   
2   -0.073268 -0.202020 -0.443576  ... -0.133103 -0.200603 -0.062318   
3    0.603155 -0.202020  2.254407  ... -0.133103 -0.200603 -0.062318   
4   -0.073268 -0.202020 -0.443576  ... -0.133103 -0.200603 -0.062318   
..        ...       ...       ...  ...       ...       ...       ...   
512 -0.073268 -0.100753 -0.443576  ... -0.133103 -0.200603 -0.062318   
513 -0.073268  0.651674 -0.443576  ... -0.133103 -0.200603 -0.062318   
514 -0.073268 -0.026532 -0.443576  ... -0.133103 -0.200603 -0.062318   
515 -0.073268 -0.202020 -0.443576  ... -0.133103 -0.200603 -0.062318   
516 -0.073268 -0.202020 -0.443576  ... -0.133103 -0.200603 -0.062318   

           21        22        23        24         25        26        27  
0   -0.256865 -0.184391  2.928152 -0.062318  -0.044023 -0.172860 -0.706081  
1   -0.256865 -0.184391 -0.341512 -0.062318  -0.044023  5.785038 -0.706081  
2   -0.256865 -0.184391 -0.341512 -0.062318  -0.044023  5.785038 -0.706081  
3   -0.256865 -0.184391  2.928152 -0.062318  -0.044023 -0.172860 -0.706081  
4   -0.256865 -0.184391  2.928152 -0.062318  -0.044023 -0.172860 -0.706081  
..        ...       ...       ...       ...        ...       ...       ...  
512 -0.256865 -0.184391 -0.341512 -0.062318  -0.044023 -0.172860 -0.706081  
513 -0.256865 -0.184391 -0.341512 -0.062318  -0.044023 -0.172860 -0.706081  
514 -0.256865 -0.184391 -0.341512 -0.062318  -0.044023 -0.172860 -0.706081  
515 -0.256865 -0.184391 -0.341512 -0.062318  -0.044023 -0.172860 -0.706081  
516 -0.256865 -0.184391 -0.341512 -0.062318  22.715633 -0.172860 -0.706081  

[517 rows x 28 columns]

In [110]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=0)

In [111]:
clf = SVC()
param_grid = [{'kernel':['rbf'],'gamma':[60,50,5,10,0.5],'C':[20,15,14,13,12,11,10,0.1,0.001] }]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(x_train,y_train)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [20, 15, 14, 13, 12, 11, 10, 0.1, 0.001],
                          'gamma': [60, 50, 5, 10, 0.5], 'kernel': ['rbf']}])

In [112]:
gsv.best_params_ , gsv.best_score_ 

({'C': 20, 'gamma': 60, 'kernel': 'rbf'}, 0.7451951951951952)

In [113]:
clf = SVC(C= 20, gamma = 60)
clf.fit(x_train , y_train)
y_pred = clf.predict(x_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 71.15384615384616


array([[  2,  44],
       [  1, 109]])